name: eshop
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12

  animated_splash_screen: ^1.3.0

  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.3


  file_picker: ^10.2.0

  # firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0

  # supabase
  supabase_flutter: ^2.9.1

  # icon
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # state management
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2

  get_storage: ^2.1.1

  dartz: ^0.10.1


  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.1.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1


  # json
  json_annotation: ^4.9.0

  get: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/images/brand/
    - assets/images/category/
    - assets/images/banner/
    - assets/images/product/
    - assets/images/user/
    - assets/images/payment/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/app_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
