// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9-FXWAP15_Yr02xkYRloLcsg7zI54WAA',
    appId: '1:695054292301:web:c6d4098d8d52094cfd1304',
    messagingSenderId: '695054292301',
    projectId: 'eshop-6d120',
    authDomain: 'eshop-6d120.firebaseapp.com',
    storageBucket: 'eshop-6d120.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCScgBk-e10MVHs741jB1DhSSEhwNrJiU4',
    appId: '1:695054292301:android:c0bf240638c3782afd1304',
    messagingSenderId: '695054292301',
    projectId: 'eshop-6d120',
    storageBucket: 'eshop-6d120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7zSvL7s8GWXEUr7oayafI2u55VhzQkto',
    appId: '1:695054292301:ios:04841b884718743ffd1304',
    messagingSenderId: '695054292301',
    projectId: 'eshop-6d120',
    storageBucket: 'eshop-6d120.firebasestorage.app',
    androidClientId: '695054292301-70osa7t8bbh4hnhf9dm7vbi49287o8fj.apps.googleusercontent.com',
    iosClientId: '695054292301-es1rhci59gc7kpu6vsihancoq7offb5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7zSvL7s8GWXEUr7oayafI2u55VhzQkto',
    appId: '1:695054292301:ios:04841b884718743ffd1304',
    messagingSenderId: '695054292301',
    projectId: 'eshop-6d120',
    storageBucket: 'eshop-6d120.firebasestorage.app',
    androidClientId: '695054292301-70osa7t8bbh4hnhf9dm7vbi49287o8fj.apps.googleusercontent.com',
    iosClientId: '695054292301-es1rhci59gc7kpu6vsihancoq7offb5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9-FXWAP15_Yr02xkYRloLcsg7zI54WAA',
    appId: '1:695054292301:web:9daf61cb9759a862fd1304',
    messagingSenderId: '695054292301',
    projectId: 'eshop-6d120',
    authDomain: 'eshop-6d120.firebaseapp.com',
    storageBucket: 'eshop-6d120.firebasestorage.app',
  );

}